/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : Time,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});
export const InquiryStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : InquiryStatus,
  'createdAt' : Time,
  'email' : IDL.Opt(IDL.Text),
  'preferredDeliveryDate' : IDL.Text,
  'message' : IDL.Text,
  'occasion' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Testimonial], []),
  'createInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        InquiryStatus,
      ],
      [Inquiry],
      [],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : Time,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const InquiryStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : InquiryStatus,
    'createdAt' : Time,
    'email' : IDL.Opt(IDL.Text),
    'preferredDeliveryDate' : IDL.Text,
    'message' : IDL.Text,
    'occasion' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [Testimonial],
        [],
      ),
    'createInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          InquiryStatus,
        ],
        [Inquiry],
        [],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };