/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : bigint,
  'customerName' : string,
  'status' : InquiryStatus,
  'createdAt' : Time,
  'email' : [] | [string],
  'preferredDeliveryDate' : string,
  'message' : string,
  'occasion' : string,
  'phone' : string,
}
export type InquiryStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : string,
}
export interface Testimonial {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : Time,
  'reviewText' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addTestimonial' : ActorMethod<[string, string, bigint], Testimonial>,
  'createInquiry' : ActorMethod<
    [string, string, [] | [string], string, string, string, InquiryStatus],
    Inquiry
  >,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'initialize' : ActorMethod<[], undefined>,
  'updateInquiryStatus' : ActorMethod<[bigint, InquiryStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];